image:
  repository: holdenk/ray-x86-and-l4t
  tag: b20092023
  pullPolicy: Always
head:
  resources:
    requests:
      memory: 20G
      ephemeral-storage: 20Gi
    limits:
      memory: 20G
      ephemeral-storage: 25Gi
  nodeSelector:
    node.kubernetes.io/gpu: gpu
worker:
  resources:
    requests:
      memory: 16G
      ephemeral-storage: 20Gi
    limits:
      memory: 16G
      ephemeral-storage: 25Gi
  nodeSelector:
    node.kubernetes.io/gpu: gpu
