apiVersion: v1
kind: Service
metadata:
  name: model-backend-svc
  namespace: totallylegitco
spec:
  selector:
    model_server: present
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
  sessionAffinity: None

